# Generated by Django 2.1.15 on 2020-05-27 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200527_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='vote_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
